version: '3'
services:
  app:
    image: node:lts
    container_name: jeus-node-js
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./src:/src
    working_dir: "/src"
    tty: true
    command: >
        bash -c "npm install &&
        npm install nodemon -g &&
        nodemon src/server.js"